# Customer Shopping Trends (E-Commerce Project)
---

## 📊 About the Dataset

This dataset provides a comprehensive look at **Sample Sales Data**, covering order information, sales figures, customer details, and shipping status. It is highly effective for retail analytics, specifically for tasks such as:

* **Customer Segmentation:** Grouping customers based on behavior.
* **Customer Analytics:** Understanding purchasing patterns.
* **Clustering:** Applying machine learning to identify hidden structures.
* **Sales Simulation:** Ideal for training in sales forecasting and business logic.

---

### 📝 Background & History
* **Original Purpose:** Initially designed for **Pentaho DI Kettle** data integration demonstrations.
* **Current Use:** Repurposed for **Sales Simulation training** and general data science practice.
* **Key Modification:** Updated and modified by **Gus Segura** in June 2014.

### 👤 Credits & Attribution
* **Original Author:** [María Carina Roldán](https://ar.linkedin.com/in/mariacarinaroldan), Pentaho Community Member & BI Consultant (Assert Solutions, Argentina).
* **License:** Licensed under the [Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License](https://creativecommons.org/licenses/by-nc-sa/3.0/).

---
---

## 📖 Data Dictionary

This section provides a detailed breakdown of the features included in the `shopping_trends.csv` dataset.

| Column Name | Description | Data Type |
| :--- | :--- | :--- |
| **Customer ID** | Unique identifier assigned to each customer. | Integer |
| **Age** | The age of the customer. | Integer |
| **Gender** | Gender of the customer (e.g., Male, Female). | Categorical |
| **Item Purchased** | The specific product bought in the transaction. | Categorical |
| **Category** | The broad classification of the item (e.g., Clothing, Accessories). | Categorical |
| **Purchase Amount (USD)** | The total value of the purchase in US Dollars. | Integer |
| **Location** | The US State where the transaction was processed. | Categorical |
| **Size** | The size of the purchased item (e.g., S, M, L, XL). | Categorical |
| **Color** | The color variant of the product. | Categorical |
| **Season** | The specific season of the purchase (Spring, Summer, Fall, Winter). | Categorical |
| **Review Rating** | Customer satisfaction score for the item (1.0 to 5.0). | Float |
| **Subscription Status** | Whether the customer has an active membership (Yes/No). | Boolean |
| **Payment Method** | The method used for payment (e.g., Credit Card, PayPal, Venmo). | Categorical |
| **Shipping Type** | The delivery method selected (e.g., Express, Free Shipping). | Categorical |
| **Discount Applied** | Indicates if a discount was applied to the order (Yes/No). | Boolean |
| **Promo Code Used** | Indicates if a promotional code was used (Yes/No). | Boolean |
| **Previous Purchases** | Total number of prior transactions by the customer. | Integer |
| **Preferred Payment Method** | The customer's top-choice payment option for future use. | Categorical |
| **Frequency of Purchases** | How often the customer shops (e.g., Weekly, Monthly, Bi-Weekly). | Categorical |

---

In [1]:
# Prepare Environment
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# 1st step : Read Data -> read_csv

Data = pd.read_csv(r"D:\Courses\DEPI R4 - Microsoft ML\Technical\Datasets\Data Analysis\shopping_trends.csv")

# Display it

display(Data.head())

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

## ✔️ Data Integrity
---

In [3]:
# Initial overview of the data

Data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   str
 3   Item Purchased            3900 non-null   str
 4   Category                  3900 non-null   str
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   str
 7   Size                      3900 non-null   str
 8   Color                     3900 non-null   str
 9   Season                    3900 non-null   str
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   str
 12  Payment Method            3900 non-null   str
 13  Shipping Type             3900 non-null   str
 14  Discount Applied          3900 non-null   str
 15  Promo Code Used           3900 non-null   str
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   str
 18  Frequency of Purchases    3900 non-null   str
dtypes: float64(1), int64(4), str(14)
memory usage: 579.0 KB

In [4]:
# Statistical overview of the data

Data.describe() # Everything is fine

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
# Searching for duplicate values

Duplicates = Data.duplicated().sum() # No Duplicates

print("Number of Duplicates:", Duplicates)

Number of Duplicates: 0

In [6]:
# Searching for null values

Nulls = Data.isnull().sum()

display(pd.DataFrame(Nulls).T) # No Nulls

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 💎 Feature Engineering
---

In [7]:
# Let's do magic

# Annual Frequency

Frequency_map = {"Fortnightly": 26, "Weekly": 52, "Annually": 1, "Quarterly": 4, "Monthly": 12, "Every 3 Months": 4, "Bi-Weekly": 26}

Data["Frequency of Purchases"] = Data["Frequency of Purchases"].map(Frequency_map, na_action="ignore")

In [8]:
# Display Data now

display(Data.sample(5))

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
1319,1320,65,Male,Sunglasses,Accessories,24,Oklahoma,M,Magenta,Spring,4.0,No,Credit Card,Standard,Yes,Yes,48,Bank Transfer,52
936,937,31,Male,Shoes,Footwear,84,Maine,M,Pink,Summer,2.7,Yes,Debit Card,Free Shipping,Yes,Yes,28,Cash,52
2032,2033,46,Male,Blouse,Clothing,36,South Carolina,M,Maroon,Winter,4.2,No,Credit Card,Next Day Air,No,No,13,Cash,1
2005,2006,18,Male,Sandals,Footwear,82,Tennessee,M,Cyan,Winter,3.4,No,PayPal,Store Pickup,No,No,30,PayPal,26
3599,3600,37,Female,Scarf,Accessories,34,Kansas,S,Peach,Spring,4.6,No,Cash,Express,No,No,4,Cash,52

In [9]:
# Customer Lifetime Value (LTV)

# Projected Annual Revenue  = Frequency * Purchase Amount

Data["Annual Revenue"] = Data["Frequency of Purchases"] * Data["Purchase Amount (USD)"]

In [10]:
# Display Data now

display(Data.sample(5))

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Annual Revenue
2747,2748,18,Female,Jeans,Clothing,62,West Virginia,M,Teal,Winter,3.1,No,Debit Card,Free Shipping,No,No,21,Credit Card,4,248
831,832,66,Male,Gloves,Accessories,63,Washington,M,Red,Summer,4.3,Yes,Debit Card,Express,Yes,Yes,47,Cash,4,252
812,813,64,Male,Boots,Footwear,56,Alaska,M,Olive,Summer,3.2,Yes,PayPal,Standard,Yes,Yes,32,Credit Card,52,2912
1064,1065,34,Male,Hat,Accessories,28,Wyoming,M,Violet,Spring,3.5,No,Debit Card,Express,Yes,Yes,42,Credit Card,4,112
3511,3512,69,Female,Jewelry,Accessories,81,Mississippi,M,Blue,Summer,3.9,No,Venmo,2-Day Shipping,No,No,21,Credit Card,4,324

In [11]:
# Binning

# Create Age Groups

Labels = ["Young", "Adult", "Senior"]

Bins = [0, 30, 50, Data["Age"].max()]

Data["Age Group"] = pd.cut(Data["Age"], bins=Bins, labels=Labels)

In [12]:
# Display Data now

display(Data.sample(5))

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Annual Revenue,Age Group
335,336,20,Male,Sweater,Clothing,85,Oregon,L,Maroon,Spring,...,Yes,Cash,Standard,Yes,Yes,44,Venmo,4,340,Young
3540,3541,24,Female,Shorts,Clothing,95,Nevada,M,Magenta,Spring,...,No,Bank Transfer,Free Shipping,No,No,5,Bank Transfer,52,4940,Young
3839,3840,66,Female,Sandals,Footwear,29,Connecticut,M,Peach,Spring,...,No,PayPal,Free Shipping,No,No,14,Venmo,4,116,Senior
771,772,22,Male,Sweater,Clothing,68,Hawaii,L,Cyan,Fall,...,Yes,Credit Card,Next Day Air,Yes,Yes,34,Bank Transfer,26,1768,Young
1494,1495,43,Male,T-shirt,Clothing,76,Montana,M,Gray,Spring,...,No,Bank Transfer,Next Day Air,Yes,Yes,23,Bank Transfer,26,1976,Adult

In [13]:
# Encoding

Sub_map = {"Yes": 1, "No": 0}

Data["Subscription Status"] = Data["Subscription Status"].map(Sub_map, na_action="ignore")

In [14]:
# Display Data now

display(Data.sample(5))

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Annual Revenue,Age Group
686,687,70,Male,Sweater,Clothing,35,Indiana,L,Beige,Fall,...,1,PayPal,2-Day Shipping,Yes,Yes,33,Venmo,26,910,Senior
257,258,20,Male,Handbag,Accessories,53,West Virginia,M,Red,Summer,...,1,PayPal,Express,Yes,Yes,5,Credit Card,4,212,Young
998,999,51,Male,Shoes,Footwear,90,Connecticut,M,White,Spring,...,1,Venmo,Next Day Air,Yes,Yes,48,Bank Transfer,26,2340,Senior
1496,1497,63,Male,T-shirt,Clothing,98,Idaho,M,Purple,Winter,...,0,Credit Card,Standard,Yes,Yes,9,Venmo,26,2548,Senior
3722,3723,23,Female,Jacket,Outerwear,34,Kentucky,XL,Yellow,Fall,...,0,PayPal,Standard,No,No,1,Credit Card,26,884,Young

## 💰 Business Intelligence Questions
---

In [15]:
# Deal Hunters vs. Loyal

Avg_Previous_Purchases	= Data.groupby("Promo Code Used")["Previous Purchases"].mean()

display(pd.DataFrame(Avg_Previous_Purchases))

                 Previous Purchases
Promo Code Used
No                        25.056230
Yes                       25.742993

In [16]:
Conditions = [(Data["Subscription Status"] == 1) | (Data["Previous Purchases"] > 25), (Data["Promo Code Used"] == "Yes") | (Data["Previous Purchases"] < 10)]
Choices = ["Loyal", "Deal Hunter"]

Data["Customer Type"] = np.select(Conditions, Choices, default="Regular")

In [17]:
# Display Data now

display(Data.sample(5))

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Annual Revenue,Age Group,Customer Type
2062,2063,54,Male,Coat,Outerwear,63,South Carolina,L,Silver,Fall,...,PayPal,Standard,No,No,15,Cash,4,252,Senior,Regular
534,535,65,Male,Gloves,Accessories,72,Florida,L,Pink,Fall,...,Bank Transfer,Next Day Air,Yes,Yes,4,PayPal,4,288,Senior,Loyal
667,668,34,Male,Sunglasses,Accessories,76,Arizona,S,Blue,Winter,...,Debit Card,Standard,Yes,Yes,32,Bank Transfer,4,304,Adult,Loyal
1187,1188,56,Male,Hat,Accessories,89,Iowa,L,Maroon,Fall,...,Cash,Express,Yes,Yes,37,Credit Card,4,356,Senior,Loyal
2901,2902,41,Female,Blouse,Clothing,43,Alabama,L,Olive,Winter,...,Credit Card,Free Shipping,No,No,46,Credit Card,4,172,Adult,Loyal

In [18]:
Pivot_table = Data.pivot_table(index="Customer Type", values="Purchase Amount (USD)", aggfunc=["count", "mean", "sum"])

Pivot_table.columns = ["Count", "Mean", "Sum"]
Pivot_table = Pivot_table.reset_index()

display(Pivot_table)

  Customer Type  Count       Mean     Sum
0   Deal Hunter    757  60.804491   46029
1         Loyal   2443  59.976259  146522
2       Regular    700  57.900000   40530

In [19]:
# The Fashion Trend

Seasonal_Tren = Data.groupby(["Season", "Color"]).size()

Most_Color_per_Season = Seasonal_Tren.groupby(level=0).idxmax().apply(lambda x: x[1])

print(Most_Color_per_Season)

Season
Fall      Magenta
Spring      Olive
Summer     Silver
Winter      Green
dtype: str

In [20]:
most_color_with_count = Seasonal_Tren.groupby(level=0).max().reset_index()
most_color_with_count.columns = ['Season', 'Count']
most_color_with_count['Most_Color'] = Most_Color_per_Season.values

print(most_color_with_count)

   Season  Count Most_Color
0    Fall     50    Magenta
1  Spring     52      Olive
2  Summer     59     Silver
3  Winter     50      Green

In [22]:
Pivot_table2 = Data.pivot_table(index="Location",columns="Shipping Type", values="Review Rating", aggfunc=["mean"])

Pivot_table2 = Pivot_table2.reset_index().sort_values(by=('mean', 'Express'), ascending=True)

display(Pivot_table2)

                     Location           mean                          \
Shipping Type                 2-Day Shipping   Express Free Shipping
20              Massachusetts       3.592857  3.333333      3.862500
6                 Connecticut       3.668750  3.463636      3.683333
36                     Oregon       3.963158  3.483333      3.554545
10                     Hawaii       3.971429  3.515385      3.470000
26                   Nebraska       3.800000  3.525000      3.733333
44                    Vermont       3.705882  3.545455      3.846154
43                       Utah       3.912500  3.560000      3.731250
4                  California       3.907143  3.581250      3.668750
9                     Georgia       3.569231  3.584615      3.600000
35                   Oklahoma       3.720000  3.588235      3.400000
24                   Missouri       3.812500  3.593750      3.746154
42                      Texas       4.028571  3.608333      3.889474
40               South Dakota       3.626667  3.628571      3.628571
11                      Idaho       3.600000  3.635714      3.987500
17                  Louisiana       4.050000  3.653846      3.857143
29                 New Jersey       4.054545  3.658333      3.740000
47              West Virginia       3.433333  3.669231      3.593333
31                   New York       3.878571  3.684615      3.915000
12                   Illinois       3.746154  3.688235      3.721429
7                    Delaware       3.800000  3.707143      3.720000
30                 New Mexico       3.633333  3.723077      3.726667
33               North Dakota       3.928571  3.731579      3.872222
27                     Nevada       3.920000  3.736364      3.570588
45                   Virginia       3.566667  3.741176      3.700000
8                     Florida       3.590000  3.764286      3.570588
15                     Kansas       3.733333  3.766667      3.783333
49                    Wyoming       3.937500  3.784615      3.570000
32             North Carolina       3.871429  3.787500      4.026667
14                       Iowa       3.514286  3.828571      3.480000
41                  Tennessee       3.694118  3.830000      3.966667
22                  Minnesota       3.540000  3.833333      3.853846
16                   Kentucky       3.566667  3.835000      3.733333
23                Mississippi       4.025000  3.870000      3.560000
37               Pennsylvania       3.842857  3.891667      3.940000
5                    Colorado       3.533333  3.900000      3.700000
18                      Maine       4.111111  3.911765      3.765000
0                     Alabama       3.900000  3.920000      3.533333
3                    Arkansas       3.375000  3.943750      3.607143
38               Rhode Island       4.042857  3.950000      3.171429
1                      Alaska       3.476923  3.953846      3.407143
28              New Hampshire       3.900000  3.961538      3.472727
13                    Indiana       3.738462  3.964286      3.641667
19                   Maryland       3.850000  4.023077      3.726667
25                    Montana       3.778947  4.042857      3.781818
48                  Wisconsin       3.850000  4.045455      4.007692
46                 Washington       3.515385  4.050000      4.028571
2                     Arizona       3.390000  4.058333      3.580000
34                       Ohio       3.966667  4.128571      3.807692
39             South Carolina       3.753846  4.185714      3.358333
21                   Michigan       3.725000  4.210000      3.660000


Shipping Type Next Day Air  Standard Store Pickup
20                3.905263  3.928571     3.372727
6                 3.538889  4.033333     3.813333
36                3.707692  3.825000     4.042857
10                3.436364  3.800000     3.914286
26                3.741667  3.925000     3.678947
44                3.692857  3.675000     3.840000
43                3.286667  3.793333     4.028571
4                 3.870000  4.193750     3.776923
9                 3.800000  3.775000     3.561111
35                3.542857  3.838462     3.561111
24                3.792308  3.726316     3.891667
42                4.245455  3.791667     3.943750
40                3.600000  3.858333     3.718182
11                3.500000  4.157143     3.822222
17                3.725000  3.707143     3.672727
29                3.718182  3.850000     3.581818
47                3.471429  3.500000     3.786667
31                3.700000  3.713333     3.430000
12                3.955556  3.333333     3.591667
7                 3.637500  3.966667     4.076923
30                3.756250  3.525000     4.000000
33                3.866667  3.458333     3.590909
27                3.733333  3.762500     3.500000
45                4.000000  3.788235     3.427273
8                 3.750000  3.892308     3.383333
15                3.618182  4.130000     3.811111
49                3.908333  3.590909     3.500000
32                3.300000  3.976923     3.866667
14                3.966667  4.050000     4.011765
41                3.850000  3.469231     3.938462
22                3.700000  4.068750     3.500000
16                3.775000  3.607692     3.892308
23                3.876923  3.745455     3.493333
37                3.585714  3.581818     3.812500
5                 4.000000  3.621429     3.705556
18                3.850000  3.753846     3.740000
0                 3.841176  3.975000     3.521053
3                 3.688235  4.063636     3.633333
38                3.818182  3.692857     3.650000
1                 4.237500  4.070588     3.771429
28                3.254545  3.644444     3.420000
13                4.130000  3.910000     3.625000
19                3.620000  3.938889     3.514286
25                3.693333  4.035294     3.643750
48                3.675000  3.993750     3.736364
46                3.553846  3.611111     4.041667
2                 3.427273  3.830000     3.808333
34                3.627273  3.709091     3.717647
39                3.800000  3.742857     3.622222
21                3.955556  3.956250     3.500000

In [23]:
# VIP Customers

VIP_THR = Data["Annual Revenue"].quantile(0.9)
VIP_Customers = Data[Data["Annual Revenue"] > VIP_THR]

display(VIP_Customers)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Annual Revenue,Age Group,Customer Type
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Cash,Free Shipping,Yes,Yes,23,Credit Card,52,3796,Adult,Loyal
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,PayPal,Next Day Air,Yes,Yes,49,PayPal,52,4680,Young,Loyal
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,...,Debit Card,Express,Yes,Yes,31,PayPal,52,2652,Senior,Loyal
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,...,PayPal,Free Shipping,Yes,Yes,34,Debit Card,52,2756,Senior,Loyal
23,24,31,Male,Pants,Clothing,88,Oklahoma,XL,White,Winter,...,Credit Card,Express,Yes,Yes,40,Credit Card,52,4576,Adult,Loyal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3828,3829,42,Female,Blouse,Clothing,82,Mississippi,M,Charcoal,Spring,...,Venmo,Free Shipping,No,No,8,Cash,52,4264,Adult,Deal Hunter
3837,3838,45,Female,Hoodie,Clothing,100,New Mexico,M,Green,Spring,...,Debit Card,Free Shipping,No,No,33,Bank Transfer,26,2600,Adult,Loyal
3852,3853,65,Female,Hat,Accessories,79,Mississippi,M,Peach,Fall,...,Credit Card,2-Day Shipping,No,No,19,PayPal,52,4108,Senior,Regular
3864,3865,55,Female,T-shirt,Clothing,99,Wyoming,S,Blue,Winter,...,Bank Transfer,Express,No,No,1,Debit Card,26,2574,Senior,Deal Hunter
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,...,PayPal,Express,No,No,24,Venmo,52,4004,Adult,Regular

In [24]:
VIP_Shipping_Distribution = VIP_Customers["Shipping Type"].value_counts(normalize=True) * 100
print(VIP_Shipping_Distribution)

Shipping Type
Free Shipping     20.312500
Express           17.968750
Standard          17.447917
Store Pickup      17.187500
Next Day Air      14.322917
2-Day Shipping    12.760417
Name: proportion, dtype: float64

In [25]:
# Age vs. Our Business

age_purchase_total = Data.groupby("Age Group")["Purchase Amount (USD)"].sum().reset_index()
print(age_purchase_total)

  Age Group  Purchase Amount (USD)
0     Young                  57279
1     Adult                  87322
2    Senior                  88480

In [28]:
Top_Customers = Data.sort_values(by="Annual Revenue", ascending=False).reset_index(drop=True)

Top_Customers

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Annual Revenue,Age Group,Customer Type
0,2215,50,Male,Belt,Accessories,100,Idaho,L,Gold,Fall,...,Cash,Standard,No,No,20,Debit Card,52,5200,Adult,Regular
1,1848,46,Male,Sandals,Footwear,100,Arizona,XL,Cyan,Summer,...,Debit Card,Free Shipping,No,No,49,Credit Card,52,5200,Adult,Loyal
2,249,47,Male,Belt,Accessories,100,Pennsylvania,M,Blue,Winter,...,Venmo,Express,Yes,Yes,33,PayPal,52,5200,Adult,Loyal
3,1480,48,Male,Coat,Outerwear,100,Washington,L,Black,Spring,...,Debit Card,Standard,Yes,Yes,2,Bank Transfer,52,5200,Adult,Deal Hunter
4,993,46,Male,Jacket,Outerwear,99,Louisiana,M,Gray,Winter,...,Credit Card,Express,Yes,Yes,50,Debit Card,52,5148,Adult,Loyal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,2302,37,Male,Pants,Clothing,20,Maine,L,Turquoise,Winter,...,Debit Card,Next Day Air,No,No,21,Debit Card,1,20,Adult,Regular
3896,587,45,Male,Hoodie,Clothing,20,Wisconsin,S,Blue,Winter,...,Venmo,2-Day Shipping,Yes,Yes,9,Venmo,1,20,Adult,Loyal
3897,256,43,Male,Scarf,Accessories,20,Maryland,M,Charcoal,Spring,...,Debit Card,Free Shipping,Yes,Yes,25,Debit Card,1,20,Adult,Loyal
3898,445,48,Male,Dress,Clothing,20,California,M,Red,Summer,...,Debit Card,Store Pickup,Yes,Yes,31,Debit Card,1,20,Adult,Loyal
3899,27,38,Male,Jewelry,Accessories,20,Nevada,M,Red,Spring,...,Cash,Next Day Air,Yes,Yes,13,Credit Card,1,20,Adult,Loyal

In [29]:
Top_5_customer = Top_Customers.loc[0:4, ["Customer ID", "Annual Revenue"]]

display(pd.DataFrame(Top_5_customer))

   Customer ID  Annual Revenue
0         2215            5200
1         1848            5200
2          249            5200
3         1480            5200
4          993            5148

In [30]:
# Payments by Age

Payment_by_Age = pd.crosstab(Data["Age Group"], Data["Payment Method"], normalize="index")* 100

display(Payment_by_Age)

Payment Method,Bank Transfer,Cash,Credit Card,Debit Card,PayPal,Venmo
Age Group,,,,,,
Young,16.649104,15.911486,16.649104,17.070601,18.335090,15.384615
Adult,16.000000,16.000000,18.372881,16.745763,15.864407,17.016949
Senior,16.124661,17.682927,18.089431,15.176152,15.582656,17.344173